apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
subjects:
  - kind: User
    name: mahendra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader